### ISSUE TITLE
hosts_redirect模块不生效

### ISSUE THREAD

**Issue by DuTh126** [lzghzr/APatch_kpm#7]
设备信息
![Screenshot_2024-08-02-13-53-10-78_26ccd656f4ada08d09da6514b90ed2c0](https://github.com/user-attachments/assets/b881c690-f125-43b8-aaa8-9636cde0c74c)
在加载模块后adb文件夹内没出现hosts相关的，嵌入后重启也是这样。需要提供些什么？

**Comment by lzghzr** [comment]
需要自己手动创建

**Comment by DuTh126** [comment]
> 需要自己手动创建

好的，打扰了，谢谢。
